language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - ~/.npm
notifications:
  email: false
install:
  - npm install
  - npm install semantic-release @semantic-release/git @semantic-release/changelog --no-save
script:
  - npm run build
  - npm run test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
