language: node_js
script:
  - npm run test
  - npm run build
branches:
  only:
    - master
install:
  - npm install standard-version
  - npx standard-version
  - git push --follow-tags https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG HEAD:$TRAVIS_BRANCH
