language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - ~/.npm
notifications:
  email: false
install:
  - npm install
  - npm install semantic-release @semantic-release/git @semantic-release/changelog --no-save
script:
  # - npm run cover
#   - npm run build
after_success:
  - npx travis-deploy-once "npm run semantic-release"
